name: Create LaTeX thesis release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version in format X.X.X'
        required: true
        default: '1.0.0'
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          extra_fonts: |
            ./font/calibri-regular.ttf
            ./font/calibri-bold.ttf
          extra_system_packages: inkscape

      - name: Rename output file
        run: mv main.pdf mg-thesis.pdf

      - name: Create tag v${{ github.event.inputs.version }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ github.event.inputs.version }}
          tag_exists_error: true
          message: "Release ${{ github.event.inputs.version }}"
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/mg-thesis.pdf
          tag_name: v${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
